SET(SDL2DIR	${CMAKE_SOURCE_DIR}/../install/sdl)

FIND_PATH(SDL2_INCLUDE_DIR 
	NAMES SDL.h
	HINTS ${SDL2DIR}
	PATH_SUFFIXES include/SDL2 include
)

FIND_LIBRARY(SDL2_LIBRARY
	NAMES SDL2d
	HINTS ${SDL2DIR}
	PATH_SUFFIXES lib64 lib
)

FIND_LIBRARY(SDL2MAIN_LIBRARY
	NAMES SDL2maind
	HINTS ${SDL2DIR}
	PATH_SUFFIXES lib64 lib
)

SET(SDL2_LIBRARY ${SDL2MAIN_LIBRARY} ${SDL2_LIBRARY})

SET(SDL2_LIBRARY ${SDL2_LIBRARY} CACHE STRING "Where the SDL2 Library can be found")
SET(SDL2_INCLUDE_DIR ${SDL2_INCLUDE_DIR} CACHE STRING "Where the SDL2 Includes can be found")
SET(SDL2_BINARY ${SDL2DIR}/bin CACHE STRING "Where the SDL2 Binary can be found")

INCLUDE(FindPackageHandleStandardArgs)
 
find_package_handle_standard_args(SDL2 REQUIRED_VARS SDL2_LIBRARY SDL2_INCLUDE_DIR SDL2_BINARY)